In [1]:
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

SEED = 515
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

# `TorchText` before version 0.7
Reference: https://github.com/pytorch/text/releases/tag/v0.7.0-rc3

## Build a Dataset Manually
Among the main concepts of `TorchText`, `Field` is the one that defines how data should be processed.  
The `Field` class couples tokenization, vocabularies, splitting, batching and sampling, padding, and numericalization all together. 

In [2]:
from torchtext.data import Field, LabelField, Example, Dataset, BucketIterator

TEXT = Field(tokenize='spacy', tokenizer_language='en_core_web_sm')
GENDER = Field(sequential=False)
LABEL = LabelField(dtype=torch.float)

In [3]:
# Example from dict
fields = {'T': ('text', TEXT), 
          'G': ('gender', GENDER), 
          'L': ('label', LABEL)}
raw_ex = {'T': "I like this film.", 
          'G': "f", 
          'L': "pos"}

ex = Example.fromdict(raw_ex, fields)
print(ex)
print(ex.text)
print(ex.gender)
print(ex.label)

['I', 'like', 'this', 'film', '.']
f
pos


In [4]:
# Example from list
fields = [('text', TEXT), ('gender', GENDER), ('label', LABEL)]
raw_ex = ["I like this film.", "f", "pos"]

ex = Example.fromlist(raw_ex, fields)
print(ex)
print(ex.text)
print(ex.gender)
print(ex.label)

['I', 'like', 'this', 'film', '.']
f
pos


In [5]:
# Create a Dataset
fields = [('text', TEXT), ('gender', GENDER), ('label', LABEL)]
raw_data = [["I like this film.", "f", "pos"], 
            ["I hate it.", "f", "neg"], 
            ["I have no feelings about it.", "m", "neg"], 
            ["It is my best.", "m", "pos"], 
            ["My father loves it so much and I do think so.", "f", "pos"]]

examples = [Example.fromlist(d, fields) for d in raw_data]
data = Dataset(examples, fields)
print(data)
print(data[1])
print(data[1].text)
print(data[1].gender)
print(data[1].label)

['I', 'hate', 'it', '.']
f
neg


In [6]:
TEXT.build_vocab(data)
GENDER.build_vocab(data)
LABEL.build_vocab(data)
len(TEXT.vocab), len(GENDER.vocab), len(LABEL.vocab)

(25, 3, 2)

In [7]:
BATCH_SIZE = 2

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
iterator = BucketIterator(data, batch_size=BATCH_SIZE, device=device, shuffle=True)

for batch in iterator:
    print(batch.text)

tensor([[ 3,  3],
        [15, 16],
        [ 4, 22],
        [ 2, 13],
        [ 1,  8],
        [ 1,  4],
        [ 1,  2]])
tensor([[ 7,  3],
        [12, 18],
        [19, 24],
        [ 4, 14],
        [ 5,  2],
        [20,  1],
        [ 9,  1],
        [ 3,  1],
        [11,  1],
        [23,  1],
        [ 5,  1],
        [ 2,  1]])
tensor([[ 6],
        [17],
        [21],
        [10],
        [ 2]])


## Load Pre-Trained Embeddings Manually

In [8]:
from torchtext.vocab import Vectors, Vocab

text = "I love this film very much ."
with open('assets/vector_cache/test-vecs.txt', 'w', encoding='utf-8') as f:
    for token in text.split():
        vec = ["%.6f" % vi for vi in np.random.randn(5)]
        f.write(" ".join([token] + vec))
        f.write("\n")

vecs = Vectors('test-vecs.txt', cache='assets/vector_cache')
print(vecs.stoi)
print(vecs.itos)
print(vecs.vectors)

86%|████████▌ | 6/7 [00:00<00:00, 6011.90it/s]
{'I': 0, 'love': 1, 'this': 2, 'film': 3, 'very': 4, 'much': 5, '.': 6}
['I', 'love', 'this', 'film', 'very', 'much', '.']
tensor([[-0.1316, -1.2163,  0.3154,  2.2605,  0.4316],
        [-0.4608, -0.9925, -0.2819, -1.6757,  0.3488],
        [ 0.9211, -0.0034, -1.7872, -0.5069, -0.2404],
        [ 0.2009, -2.6882,  0.1634,  0.8077,  0.0838],
        [-0.0382,  0.2052, -1.1867,  0.8228, -0.5860],
        [ 0.7365,  0.3347,  1.6088, -0.4995,  0.4200],
        [-1.1841,  0.9180,  1.0854, -0.3196, -1.1193]])


In [9]:
# Set `include_lengths=True` to return the text lengths too. 
TEXT = Field(tokenize='spacy', tokenizer_language='en_core_web_sm', include_lengths=True)
GENDER = Field(sequential=False)
LABEL = LabelField(dtype=torch.float)

# Create a Dataset
fields = [('text', TEXT), ('gender', GENDER), ('label', LABEL)]
raw_data = [["I like this film.", "f", "pos"], 
            ["I hate it.", "f", "neg"], 
            ["I have no feelings about it.", "m", "neg"], 
            ["It is my best.", "m", "pos"], 
            ["My father loves it so much and I do think so.", "f", "pos"]]

examples = [Example.fromlist(d, fields) for d in raw_data]
data = Dataset(examples, fields)
data

In [10]:
TEXT.build_vocab(data)
GENDER.build_vocab(data)
LABEL.build_vocab(data)

print(TEXT.vocab.vectors)

None


In [11]:
# The missing tokens are initialized as zeros, or by `unk_init` if provided. 
TEXT.build_vocab(data, vectors=vecs)
print(TEXT.vocab.vectors)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.1841,  0.9180,  1.0854, -0.3196, -1.1193],
        [-0.1316, -1.2163,  0.3154,  2.2605,  0.4316],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.2009, -2.6882,  0.1634,  0.8077,  0.0838],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 

In [12]:
BATCH_SIZE = 2

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
iterator = BucketIterator(data, batch_size=BATCH_SIZE, device=device, shuffle=True)

# `batch.text` is now a tuple with the second element being the text lengths.
for batch in iterator:
    print(batch.text)

(tensor([[ 3,  3],
        [15, 16],
        [ 4, 22],
        [ 2, 13],
        [ 1,  8],
        [ 1,  4],
        [ 1,  2]]), tensor([4, 7]))
(tensor([[ 7,  3],
        [12, 18],
        [19, 24],
        [ 4, 14],
        [ 5,  2],
        [20,  1],
        [ 9,  1],
        [ 3,  1],
        [11,  1],
        [23,  1],
        [ 5,  1],
        [ 2,  1]]), tensor([12,  5]))
(tensor([[ 6],
        [17],
        [21],
        [10],
        [ 2]]), tensor([5]))


## Load a Dataset from `TorchText`

In [13]:
import torchtext
from torchtext.data import Field, LabelField, BucketIterator

# Set `batch_first=True` in the `Field`.
TEXT = Field(tokenize='spacy', tokenizer_language='en_core_web_sm', include_lengths=True, batch_first=True)
LABEL = LabelField()

train_data, test_data = torchtext.datasets.TREC.splits(TEXT, LABEL, fine_grained=False, root="assets/data")
train_data, valid_data = train_data.split()

In [14]:
MAX_VOCAB_SIZE = 25000

TEXT.build_vocab(train_data, max_size=MAX_VOCAB_SIZE, 
                 vectors="glove.6B.100d", vectors_cache="assets/vector_cache", 
                 unk_init=torch.Tensor.normal_)

LABEL.build_vocab(train_data)
print(LABEL.vocab.stoi)

defaultdict(None, {'ENTY': 0, 'HUM': 1, 'DESC': 2, 'NUM': 3, 'LOC': 4, 'ABBR': 5})


In [15]:
# `Field.preprocess` has been called when building the dataset. 
# `Field.preprocess` includes `Field.preprocessing` passed by user. 

# `Field.process` process a batch of examples to create a torch.Tensor.
# `Field.process` includes padding, numericalization, and postprocess (including `Field.postprocessing` passed by user) a batch and create a tensor.
TEXT.process([train_data[0].text, train_data[1].text, train_data[2].text], device=device)

(tensor([[   4,   24,    3,  297,  552,  106,   18,    7,  286,   14,  552,    2],
         [  26,    5, 3375,  677,    2,    1,    1,    1,    1,    1,    1,    1],
         [  10,   22,   61,  443,   41,  156,   18,  107,   36,   13,  357,    2]]),
 tensor([12,  5, 12]))

In [16]:
ex = train_data[0]
print(ex.text)
# If `include_lengths=False`, it should be:  
# `TEXT.numericalize([ex.text], device=device)`
text, text_lens = TEXT.numericalize(([ex.text], [len(ex.text)]), device=device)
print(text)
print(text_lens)

['What', 'do', 'the', 'letters', 'D.C.', 'stand', 'for', 'in', 'Washington', ',', 'D.C.', '?']
tensor([[  4,  24,   3, 297, 552, 106,  18,   7, 286,  14, 552,   2]])
tensor([12])


In [17]:
BATCH_SIZE = 128

train_iterator, valid_iterator, test_iterator = BucketIterator.splits(
    (train_data, valid_data, test_data), 
    batch_size=BATCH_SIZE, sort_within_batch=True, device=device)

## `BucketIterator.splits`
By default, the first dataset (`train_iterator`) would be shuffled, while the other datasets (`valid_iterator` and `test_iterator`) would be not shuffled. 

In [18]:
for i, batch in enumerate(train_iterator):
    text, text_lens = batch.text
    print(text_lens.max(), text_lens[0], text_lens[-1])
    if i >= 9:
        break

tensor(11) tensor(11) tensor(11)
tensor(16) tensor(16) tensor(15)
tensor(6) tensor(6) tensor(5)
tensor(9) tensor(9) tensor(9)
tensor(20) tensor(20) tensor(17)
tensor(11) tensor(11) tensor(11)
tensor(10) tensor(10) tensor(10)
tensor(15) tensor(15) tensor(14)
tensor(10) tensor(10) tensor(10)
tensor(14) tensor(14) tensor(13)


In [19]:
for i, batch in enumerate(train_iterator):
    text, text_lens = batch.text
    print(text_lens.max(), text_lens[0], text_lens[-1])
    if i >= 9:
        break

tensor(14) tensor(14) tensor(13)
tensor(7) tensor(7) tensor(6)
tensor(7) tensor(7) tensor(7)
tensor(11) tensor(11) tensor(10)
tensor(11) tensor(11) tensor(11)
tensor(6) tensor(6) tensor(5)
tensor(16) tensor(16) tensor(15)
tensor(9) tensor(9) tensor(9)
tensor(10) tensor(10) tensor(9)
tensor(12) tensor(12) tensor(12)


In [20]:
for i, batch in enumerate(valid_iterator):
    text, text_lens = batch.text
    print(text_lens.max(), text_lens[0], text_lens[-1])
    if i >= 9:
        break

tensor(5) tensor(5) tensor(3)
tensor(7) tensor(7) tensor(6)
tensor(7) tensor(7) tensor(7)
tensor(8) tensor(8) tensor(7)
tensor(9) tensor(9) tensor(8)
tensor(9) tensor(9) tensor(9)
tensor(10) tensor(10) tensor(9)
tensor(11) tensor(11) tensor(10)
tensor(12) tensor(12) tensor(11)
tensor(13) tensor(13) tensor(12)


In [21]:
for i, batch in enumerate(valid_iterator):
    text, text_lens = batch.text
    print(text_lens.max(), text_lens[0], text_lens[-1])
    if i >= 9:
        break

tensor(5) tensor(5)tensor(3)
tensor(7) tensor(7) tensor(6)
tensor(7) tensor(7) tensor(7)
tensor(8) tensor(8) tensor(7)
tensor(9) tensor(9) tensor(8)
tensor(9) tensor(9) tensor(9)
tensor(10) tensor(10) tensor(9)
tensor(11) tensor(11) tensor(10)
tensor(12) tensor(12) tensor(11)
tensor(13) tensor(13) tensor(12)
