In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

SEED = 515
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

# Faster Sentiment Analysis
This notebook follows this tutorial: https://github.com/bentrevett/pytorch-sentiment-analysis.

In [2]:
def append_bigrams(x):
    bigrams = set(["%s %s" % (f, s) for f, s in zip(x[:-1], x[1:])])
    x.extend(list(bigrams))
    return x

append_bigrams("This film is the best".split())

['This',
 'film',
 'is',
 'the',
 'best',
 'This film',
 'is the',
 'film is',
 'the best']

In [3]:
import torchtext
from torchtext.data import Field, LabelField, BucketIterator

TEXT = Field(tokenize='spacy', preprocessing=append_bigrams, include_lengths=True)
LABEL = LabelField(dtype=torch.float)

train_data, test_data = torchtext.datasets.IMDB.splits(TEXT, LABEL, root='data')
train_data, valid_data = train_data.split()

In [4]:
MAX_VOCAB_SIZE = 25000

TEXT.build_vocab(train_data, max_size=MAX_VOCAB_SIZE, 
                 vectors="glove.6B.100d", vectors_cache="vector_cache", 
                 unk_init=torch.Tensor.normal_)

LABEL.build_vocab(train_data)

In [5]:
# The bi-grams are included in the `Dataset`.
print(train_data[0].text)
# The bi-grams are also included in the `TEXT.vocab`.
print(TEXT.vocab.itos[-10:])

['Given', 'how', 'corny', 'these', 'movies', 'are', ',', 'you', 'got', 'ta', 'figure', 'that', 'they', 'must', 'have', 'had', 'fun', 'making', 'them', '.', 'The', 'movie', 'focuses', 'on', 'a', 'house', 'that', 'strangely', 'accommodates', 'whomever', 'lives', 'there', '.', 'The', 'inhabitants', 'were', ':', 'author', 'Charles', 'Hillyer', '(', 'Denholm', 'Elliott', '(', 'with', 'hair', '!', ')', ')', ',', 'who', 'gets', 'haunted', 'by', 'one', 'of', 'his', 'own', 'creations', ';', 'Philip', 'Grayson', '(', 'Peter', 'Cushing', ')', ',', 'who', 'gets', 'a', 'little', 'too', 'close', 'to', 'a', 'wax', 'statue', ';', 'John', 'Reid', '(', 'Christopher', 'Lee', ')', ',', 'whose', 'daughter', "'s", 'cuteness', 'is', 'apparently', 'a', 'facade', ';', 'and', 'actor', 'Paul', 'Henderson', '(', 'Jon', 'Pertwee', ')', ',', 'on', 'the', 'verge', 'of', 'getting', 'a', 'little', 'too', 'much', 'into', 'character.<br', '/><br', '/>"The', 'House', 'That', 'Dripped', 'Blood', '"', 'is', 'actually', 'wo

In [6]:
BATCH_SIZE = 64

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_iterator, valid_iterator, test_iterator = BucketIterator.splits(
    (train_data, valid_data, test_data), 
    batch_size=BATCH_SIZE, device=device)

In [7]:
for batch in train_iterator:
    break
text, text_lens = batch.text
print(text)
print(text_lens)

tensor([[1422,   11,   68,  ..., 1365,   11,   11],
        [ 163,   79,   22,  ...,    0, 2279,   79],
        [   3, 1014,    9,  ..., 1583,  916,   73],
        ...,
        [   1,    1,    1,  ...,    1,    1,    1],
        [   1,    1,    1,  ...,    1,    1,    1],
        [   1,    1,    1,  ...,    1,    1,    1]], device='cuda:0')
tensor([ 427,  354,  572,  561,  138,  539,  417,  329,  221,  426,  252,  718,
        1237, 1014,  307,  644,  351,  706, 1642, 1592,  286,  305, 1734,  321,
          94,  466,  157,  260,   90, 1141,  389, 1230,  297,  362,  326,  101,
         840,  543,  601, 1093,  403,  314,  263,  811,  292,  555,  524,  292,
         142,  566,  413,  306,  240,  370,  524,  282,  383,  785,  294,  352,
         670,  339,  656,  276], device='cuda:0')


# Build Model

In [8]:
class Classifier(nn.Module):
    def __init__(self, in_dim, emb_dim, out_dim, pad_idx):
        super().__init__()
        self.emb = nn.Embedding(in_dim, emb_dim, padding_idx=pad_idx)
        self.fc = nn.Linear(emb_dim, out_dim)

    def forward(self, text, text_lens):
        # text: (step, batch)
        embedded = self.emb(text)
        
        # Pooling along steps
        # pooled: (batch, emb)
        pooled = embedded.sum(dim=0) / text_lens.unsqueeze(1)
        return self.fc(pooled)

In [9]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

IN_DIM = len(TEXT.vocab)
EMB_DIM = 100
OUT_DIM = 1
PAD_IDX = TEXT.vocab.stoi[TEXT.pad_token]

classifier = Classifier(IN_DIM, EMB_DIM, OUT_DIM, PAD_IDX).to(device)
count_parameters(classifier)

2500301

In [10]:
# Initialize Embeddings with Pre-Trained Vectors
classifier.emb.weight.data.copy_(TEXT.vocab.vectors)

UNK_IDX = TEXT.vocab.stoi[TEXT.unk_token]

classifier.emb.weight.data[UNK_IDX].zero_()
classifier.emb.weight.data[PAD_IDX].zero_()

print(classifier.emb.weight[:5, :8])

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344],
        [-0.1077,  0.1105,  0.5981, -0.5436,  0.6740,  0.1066,  0.0389,  0.3548],
        [-0.3398,  0.2094,  0.4635, -0.6479, -0.3838,  0.0380,  0.1713,  0.1598]],
       device='cuda:0', grad_fn=<SliceBackward>)


# Train Model

In [11]:
optimizer = optim.Adam(classifier.parameters())
# Binary cross entropy with logits. 
# The binary version of cross entropy loss. 
loss_func = nn.BCEWithLogitsLoss().to(device)

In [12]:
def train_epoch(classifier, iterator, optimizer, loss_func):
    classifier.train()
    epoch_loss = 0
    epoch_acc = 0
    for batch in iterator:
        # Forward pass
        text, text_lens = batch.text
        preds = classifier(text, text_lens).squeeze(-1)
        # Calculate loss
        loss = loss_func(preds, batch.label)
        # Backward propagation
        optimizer.zero_grad()
        loss.backward()
        # Update weights
        optimizer.step()
        # Accumulate loss and acc
        epoch_loss += loss.item()
        epoch_acc += (torch.round(torch.sigmoid(preds)) == batch.label).sum().item() / preds.size(0)
    return epoch_loss/len(iterator), epoch_acc/len(iterator)

def eval_epoch(classifier, iterator, loss_func):
    classifier.eval()
    epoch_loss = 0
    epoch_acc = 0
    with torch.no_grad():
        for batch in iterator:
            # Forward pass
            text, text_lens = batch.text
            preds = classifier(text, text_lens).squeeze(-1)
            # Calculate loss
            loss = loss_func(preds, batch.label)
            # Accumulate loss and acc
            epoch_loss += loss.item()
            epoch_acc += (torch.round(torch.sigmoid(preds)) == batch.label).sum().item() / preds.size(0)
    return epoch_loss/len(iterator), epoch_acc/len(iterator)

In [13]:
import time
N_EPOCHS = 5
best_valid_loss = np.inf

for epoch in range(N_EPOCHS):
    t0 = time.time()
    train_loss, train_acc = train_epoch(classifier, train_iterator, optimizer, loss_func)
    valid_loss, valid_acc = eval_epoch(classifier, valid_iterator, loss_func)
    epoch_secs = time.time() - t0

    epoch_mins, epoch_secs = int(epoch_secs // 60), int(epoch_secs % 60)
    
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(classifier.state_dict(), 'models/tut3-model.pt')
    
    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

Epoch: 01 | Epoch Time: 0m 7s
	Train Loss: 0.669 | Train Acc: 66.01%
	 Val. Loss: 0.625 |  Val. Acc: 74.74%
Epoch: 02 | Epoch Time: 0m 7s
	Train Loss: 0.547 | Train Acc: 80.22%
	 Val. Loss: 0.482 |  Val. Acc: 82.79%
Epoch: 03 | Epoch Time: 0m 7s
	Train Loss: 0.410 | Train Acc: 86.42%
	 Val. Loss: 0.385 |  Val. Acc: 85.84%
Epoch: 04 | Epoch Time: 0m 7s
	Train Loss: 0.325 | Train Acc: 89.25%
	 Val. Loss: 0.335 |  Val. Acc: 87.12%
Epoch: 05 | Epoch Time: 0m 7s
	Train Loss: 0.275 | Train Acc: 90.78%
	 Val. Loss: 0.305 |  Val. Acc: 88.28%


In [14]:
classifier.load_state_dict(torch.load('models/tut3-model.pt'))

valid_loss, valid_acc = eval_epoch(classifier, valid_iterator, loss_func)
test_loss, test_acc = eval_epoch(classifier, test_iterator, loss_func)

print(f'Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}%')
print(f'Test Loss: {test_loss:.3f} | Test Acc: {test_acc*100:.2f}%')

Val. Loss: 0.305 | Val. Acc: 88.28%
Test Loss: 0.314 | Test Acc: 87.72%


# User Input

In [15]:
import spacy
nlp = spacy.load('en')

def predict_senti(classifier, sentence):
    classifier.eval()
    tokenized = [tok.text for tok in nlp.tokenizer(sentence)]
    indexed = [TEXT.vocab.stoi[tok] for tok in tokenized]
    lens = len(indexed)

    indexed = torch.tensor(indexed, dtype=torch.long).unsqueeze(1).to(device)
    lens = torch.tensor(lens, dtype=torch.long).unsqueeze(0).to(device)
    pred = torch.sigmoid(classifier(indexed, lens)).round().type(torch.long)
    return LABEL.vocab.itos[pred.item()]

In [16]:
predict_senti(classifier, "This is a good film.")

'pos'

In [17]:
predict_senti(classifier, "This film is terrible.")

'neg'

# Check Embeddings
* The Embeddings of `unk` and `<pad>` tokens
    * Because the `padding_idx` has been passed to `nn.Embedding`, so the `<pad>` embedding will remain zeros throughout training.  
    * While the `<unk>` embedding will be learned.

In [18]:
print(classifier.emb.weight[:5, :8])

tensor([[ 0.0193, -0.0252, -0.0565, -0.0322, -0.0053,  0.0131, -0.0153, -0.0453],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.1143, -0.1685,  0.7600, -0.3274,  0.1637, -0.0413, -0.3092,  0.4015],
        [-0.1759,  0.1776,  0.6234, -0.4766,  0.7496,  0.0301,  0.1125,  0.4083],
        [-0.3518,  0.2210,  0.4499, -0.6349, -0.3693,  0.0153,  0.1888,  0.1646]],
       device='cuda:0', grad_fn=<SliceBackward>)
